#ifndef SETTLERS_OF_CATAN_DEVELOPMENTCARD_H_
#define SETTLERS_OF_CATAN_DEVELOPMENTCARD_H_

enum ProgressCard {
	KNIGHT,
	ROAD_BUILDING,
	YEAR_OF_PLENTY,
	MONOPOLY
};

#endif // SETTLERS_OF_CATAN_DEVELOPMENTCARD_H_